name: Open PR on Develop to Main

on:
  push:
    branches:
      - develop

jobs:
  open_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.email "afonsoprad10@gmail.com"
          git config user.name "GitHub Actions"

      - name: Create Pull Request
        run: |
          git fetch origin main:main
          git checkout main
          git pull origin main
          git checkout develop
          git pull origin develop
          git push origin develop
          gh pr create --base main --head develop --title "Merge develop into main" --body "Deploy on vercel."
