name: Open PR on Develop to Main

on:
  push:
    branches:
      - develop

jobs:
  open_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check existing PR
        id: check_pr
        run: |
          PR_EXISTS=$(gh pr list --base main --head develop | wc -l)
          echo "::set-output name=pr_exists::$PR_EXISTS"

      - name: Create Pull Request
        if: steps.check_pr.outputs.pr_exists == '0'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --base main --head develop --title "Merge develop into main" --body "Deploy on vercel."
